'use strict';
const {spawn}=require('child_process');
const sleep=ms=>new Promise(r=>setTimeout(r,ms)),port=9464;
const bin='C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe';
const url='file:///C:/Users/adria/adaptive-english/index.html';
const browser=spawn(bin,['--headless','--disable-gpu','--allow-file-access-from-files','--no-first-run','--remote-debugging-port='+port,'--user-data-dir='+process.env.TEMP+'\\grammar-pack-test-'+process.pid,url],{stdio:'ignore'});
(async()=>{
 let page;for(let i=0;i<140;i++){try{const all=await(await fetch('http://127.0.0.1:'+port+'/json/list')).json();page=all.find(x=>x.type==='page'&&x.url.includes('adaptive-english/index.html'));if(page)break;}catch{}await sleep(160)}
 if(!page)throw Error('No grammar page');const ws=new WebSocket(page.webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener('open',r,{once:true}));
 let n=0;const jobs=new Map();ws.addEventListener('message',ev=>{const m=JSON.parse(ev.data),j=jobs.get(m.id);if(j){jobs.delete(m.id);j(m)}});
 const cmd=expression=>new Promise(resolve=>{const id=++n;jobs.set(id,resolve);ws.send(JSON.stringify({id,method:'Runtime.evaluate',params:{expression,returnByValue:true,awaitPromise:true}}))});
 for(let i=0;i<150;i++){const x=await cmd('typeof state!=="undefined"&&!!state&&!!window.pako&&!!window.AdrianAchievements');if(x?.result?.value)break;await sleep(150)}
 const prepare='(()=>{const original=state;const words="Exercise with accented ê á and English structure: If I had known earlier, I would have told you in advance. ";for(let i=0;i<6000;i++){original.history.push({level:Math.floor(i/15)+1,qid:"unique-"+i,cat:"backshift",skill:"reported speech backshift",templateId:"backshift-"+(i%120),domain:"grammar",correct:i%4!==0,ms:2350+(i%13000),type:i%8===0?"automatic":"correct",occurrence:1,patternOccurrence:i,review:i>120,reviewDue:false,delayedRecall:false,gap:null,ts:Date.now()-i*25000,question:words+i,originalQuestion:words,userAnswer:"had gone",correctAnswer:"would have gone",rule:"With a past reporting verb and completed reporting context, use the matching backshift tense."});}for(let i=0;i<434;i++)original.sessionHistory.push({mode:"training",level:i+1,correct:i>429?15:i%5+8,total:15,avgMs:3400,automatic:.1,accuracy:.6,ts:Date.now()});original.level=496;original.sessions=434;original.totalAttempts=6622;const start=performance.now();try{save();const raw=JSON.parse(localStorage.getItem(STORAGE_KEY)),time=performance.now()-start,restored=restoreHistory(JSON.parse(JSON.stringify(raw)));return {ok:true,timeMs:Math.round(time),storedChars:JSON.stringify(raw).length,rawTail:raw.history.length,packed:!!raw.historyPackV1,packedCount:raw.historyPackV1?.count,allRows:restored.history.length,first:restored.history[0].qid,last:restored.history.at(-1).qid,gold:medalCounts().gold,sessionHistory:raw.sessionHistory.length,level:raw.level};}catch(e){return {ok:false,name:e.name,message:e.message,stack:e.stack}}})()';
 const r=await cmd(prepare);console.log('PACK',JSON.stringify(r));if(!r?.result?.value?.ok||r.result.value.allRows!==6000||r.result.value.packedCount!==5925)throw Error('History pack failed');
 const before=await cmd('({before:state.history.length,fromStorage:!!JSON.parse(localStorage.getItem(STORAGE_KEY)).historyPackV1})');console.log('BEFORE RELOAD',JSON.stringify(before));
 const reload=await new Promise(resolve=>{const id=++n;jobs.set(id,resolve);ws.send(JSON.stringify({id,method:'Page.reload',params:{ignoreCache:true}}))});
 for(let i=0;i<120;i++){const x=await cmd('typeof state!=="undefined"&&!!state&&state.history?.length===6000');if(x?.result?.value)break;await sleep(150)}
 const restored=await cmd('({level:state.level,sessions:state.sessions,history:state.history.length,first:state.history[0].qid,last:state.history.at(-1).qid,gold:medalCounts().gold,stored:!!JSON.parse(localStorage.getItem(STORAGE_KEY)).historyPackV1})');console.log('AFTER RELOAD',JSON.stringify(restored));if(restored?.result?.value?.history!==6000||restored.result.value.gold!==4)throw Error('History recovery failed');
 const finish=await cmd('(async()=>{session={records:state.history.slice(-15).map(r=>({...r,correct:true,ms:6900,type:"correct"})),correct:15,automatic:3,mode:"training",target:11,rankBefore:skillRankPositions(),learningXp:160,bestCombo:15,recovered:0,masteredRewards:0};try{await finishSession();const raw=JSON.parse(localStorage.getItem(STORAGE_KEY));return {ok:true,level:state.level,last:state.sessionHistory.at(-1).level,correct:state.sessionHistory.at(-1).correct,storedLast:raw.sessionHistory.at(-1).level,storedGold:window.AdrianAchievements.countsFromHistory(raw.sessionHistory).gold,screen:document.querySelector("#endSub").textContent,average:document.querySelector("#eAvg").textContent,mastery:document.querySelector("#eMastery").textContent};}catch(e){return {ok:false,message:e.message,stack:e.stack}}})()');console.log('FINISH',JSON.stringify(finish));if(!finish?.result?.value?.ok||finish.result.value.storedLast!==496||finish.result.value.storedGold!==5||finish.result.value.average!=='6.9s')throw Error('Gold persistence or completion UI failed');
 ws.close();
})().catch(e=>console.error('FAIL',e.stack||e)).finally(()=>{browser.kill();setTimeout(()=>process.exit(),400)});
